name: app
description: "A technical test for Prixz."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  intl: ^0.19.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
